version: '3.8'

services:
  pwnlab-24.04:
    image: pwnlab-24.04
    platform: linux/amd64
    container_name: pwnlab-24.04
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true
    ports:
      - "5001:5001"
    volumes:
      - ./challenges:/home/pwner/challenges
